### ISSUE TITLE
触发器关键词冲突

### ISSUE THREAD

**Issue by CYDXDianXian** [pcrbot/voice_generate#1]
合成语音与戳一戳集卡的前缀触发器关键词“合成”会产生冲突，故建议将合成更改为模拟

**Comment by CYDXDianXian** [comment]
不用了麻烦老师了，我去怒改集卡关键词2333

**Comment by XT-G3** [comment]
大佬，我问问这个转换cq码错误试过啥情况啊？还有这个init文件里全是空的正常吗？
![QQ截图20221014205955](https://user-images.githubusercontent.com/111116375/195853184-f68df76f-12d3-4fe2-b7a4-1591fc56924b.png)
